name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: Install pre-commit
      run: pip3 install pre-commit
    - name: Run pre-commit hooks
      run: pre-commit run -a

